app/routes/auth.py
import os
from flask import Blueprint, redirect, url_for, flash, current_app
from flask_dance.contrib.github import make_github_blueprint, github
from app.utils.decorators import login_required

auth_bp = Blueprint("auth", __name__)
github_bp = make_github_blueprint(scope= "user:email")
auth_bp.register_blueprint(github_bp)

@auth_bp.route("/signin")
def signin():
    if not github.authorized:
        return redirect(url_for("auth.github.login"))
    resp = github.get("/user/emails")
    if not resp.ok:
        return redirect(url_for("public.home"))
    emails = resp.json()
    primary_email = next((email['email'] for email in emails if email['primary']), None)
    print(primary_email)
    return redirect(url_for('private.dashboard'))

@auth_bp.route("/signout")
@login_required
def signout():
    github_bp.token = None
    return redirect(url_for('public.home'))

app/templates/dashboard.html
{% extends "layout/base.html" %}
{% block title %} Dashboard | feedbackpulse {% endblock %}
{% block content %}
<h1 class="text-white text-3xl">Dashboard</h1>
{% endblock%}

app/templates/home.html
{% extends "layout/base.html" %}
{% block title %} feedbackpulse | Home {% endblock %}

{% block content %}
<div class="flex justify-center items-center h-screen">
    <div class="backdrop-blur-xl flex flex-col gap-6 justify-center items-center md:p-6 md:py-8 p-4 py-8 rounded-xl md:w-[450px] w-[320px] z-10 border-2 border-white/40">
        <h1 class="md:text-5xl text-4xl font-sans font-extrabold text-white mb-5">
            feedbackpulse
        </h1>
        <p class="w-full md:text-md font-sans text-center text-white p-2 rounded-md border-2 border-white/40">
            Join
            <a target="_blank" href="https://team.shiksha/" class="underline italic underline-offset-4 font-sembold">
                Team.shiksha
            </a>
            projects, request feedback, provide reviews, and gain insights — all in one place.
        </p>
        <a class="text-center py-2 w-full justify-center flex gap-4 items-center text-bold text-white transition duration-200 delay-100 hover:shadow-[rgba(255,255,255,0.5)_0_0_12px_0] rounded-md border-2 border-white/40"
        href="{{ url_for('auth.signin') }}">
            <img src="{{ url_for('static', filename='images/github.svg') }}" class="h-7 animate-bounce" alt="GitHub Icon" />
            <span class="font-extrabold text-lg">Sign In with GitHub</span>
        </a>
        <p class="text-white text-center text-md mt-5">
            Built by
            <a class="underline italic underline-offset-4" href="https://team.shiksha/" target="_blank">
                Team.shiksha
            </a>. Source code available
            <a class="underline italic underline-offset-4" href="https://github.com/TeamShiksha/feedbackpulse" target="_blank">
                here
            </a>.
        </p>
    </div>
</div>
{% endblock%}

app/templates/projects.html
{% extends "layout/base.html" %}
{% block title %} Projects | feedbackpulse {% endblock %}
{% block content %}
<h1 class="text-white text-3xl">projects</h1>
{% endblock%}

app/templates/resources.html
{% extends "layout/base.html" %}
{% block title %} Resources | feedbackpulse {% endblock %}
{% block content %}
<h1 class="text-white text-3xl">resources</h1>
{% endblock%}

app/templates/snapshots.html
{% extends "layout/base.html" %}
{% block title %} Snapshots | feedbackpulse {% endblock %}
{% block content %}
<h1 class="text-white text-3xl">Snapshots</h1>
{% endblock%}